### ISSUE TITLE
some test cases in tests_chapter8.py actually cover chapter 9

### ISSUE THREAD

**Issue by erolm-a** [gerac83/rango_tests#3]
In particular:

- `test_url_reference_in_index_page_when_not_logged(self)`:
   this function calls `reverse('register')`, which is indeed a  non-existing page. If my understanding is correct it refers to the user registration page in chapter 9. Similarly, `test_titles_displayed(self)`, `test_pages_using_templates(self)` fail because there is no `register` in `rango/urls.py`.
- `test_url_reference_in_index_page_when_logged` does not work either because it requires the `restricted` page to be defined. Again, this is covered in chapter 9 only.

**Comment by gerac83** [comment]
Check decorators.py, those tests will be skipped until you complete chapter 9

**Comment by erolm-a** [comment]
I noticed those decorators, unfortunately the cases were not skipped, otherwise I wouldn't be writing the issue here.
